baseURL = "http://baturin.me/"
languageCode = "en-us"
title = "Val Baturin's Personal Pages"
publishDir = "../docs"

[params]
copyright = "baturin.me"

[[menu.main]]
weight = 1
name = "Home"
url = "/"

[[menu.main]]
weight = 2
name = "Posts"
url = "/posts/"

[[menu.main]]
weight = 3
name = "About"
url = "/about/"

[[menu.main]]
weight = 4
name = "Contact"
url = "/contact/"
